### ISSUE TITLE
Mögliche Zustände der Node

### ISSUE THREAD

**Issue by maSchoeller** [lightning-rmc/lightning#1]
Aktuell haben wir zwei Konzepte der möglichen Zustände:

## [Node.md](https://github.com/lightning-rmc/lightning/blob/main/docs/node.md)
- Active
- Needs Configuration
- Error
- Offline
## [Controlflow.md](https://github.com/lightning-rmc/lightning/blob/main/docs/controlflow.md)
- Disconnected
- Edit
- Live

Die Frage ist können die beiden Modelle zusammengefasst werden?
Oder ist _"Controlflow"_ ein möglicher unterzustand von _"Active"_.

@langmario was könnte unter _"Needs Configuration"_ fallen?

Ich würde vorschlagen wir fassen die beiden zusammen zu einem Zustandsautomaten?
Vorschlag:
- Offline        --> Die Node ist bekannt aber disconnected
- Active/Info --> der Infoscreen wird angezeigt
- Edit            --> Die Layer können bearbeitet werden
- Error          --> Es gibt ein Fehler im LayerEdit, Media ist nicht vorhanden , etc...
- Live            --> Die Nodes sind live und die Layer können aktiviert werden
- Needs Configuration(falls notwendig)

cc @Soon5

**Comment by langmario** [comment]
Zustandsautomat wollte ich noch machen, aber nachm Geschäft ;)
Bin grundsätzlich auch fürs zusammenfassen.
_"Needs Configuration"_ wären diejenigen Nodes, die sich frisch ans System angemeldet haben aber noch nicht im Controller konfiguriert (Name, Location, Output, ...) wurden und dementsprechend noch "Aufmerksamkeit" benötigen, bevor sie tatsächlich Output generieren können

Ich überarbeite die Zustände nochmal und fügs dann hier ein.

**Comment by maSchoeller** [comment]
Für _"Needs Configuration"_ ist mir nämlich nichts eingefallen. Name und Location fällt für mich eigentlich beides weg, weils in der Konfigurationsdatei  auf der Node ist, wenn die nicht vorhanden sind würde ich entweder in den _"Error"_ Zustand gehen oder die Node lässt sich garnicht erst starten.

Output konfigurieren wir ja in der Edit Page oder? Das Ergibt sich dadruch indirekt.

**Comment by langmario** [comment]
Ich will ja aber nicht wenn ich ein System mit 6 Nodes neu aufsetz vorher hingehen müssen und mich auf jede Node einzelnen aufschalten um die Konfigurationsdatei zu bearbeiten.
Ich hätte gesagt dass macht man über die Weboberfläche.
Nachdem eine für das System neue Node ans Netzwerk angeschlossen wird und sich am Controller registriert muss diese konfiguriert werden mit Name, etc... und dann ist sie fertig konfiguriert, Teil des Netzes und einsatzbereit, und vorher ist sie im Zustand "needs configuration"

Ich vergleichs mit Philips Hue, wenn ich da ne neue Lampe hab schließ ich sie an und die Hue Bridge findet sie und ich muss sie über die App konfigurieren wie einen Namen geben und einem Raum zuordnen, davor kann ich sie nicht benutzen und sie befindet sich auch in einer Art Status "Not Configured"

Ja Output war ein blödes Beispiel, hab halt irgendwelche Eigenschaften aufgezählt

**Comment by maSchoeller** [comment]
An für sich wäre das natürlich die schönere Lösung, die ist rein technisch jedoch aufwändiger.
Wir brauchen dann eine Konfiguration im RAM die mit einer Datei sychron gehalten wird. 
In dem fall würde auch die Konifuration vom ASP.NET/Generic Host wegfallen, die hat soweit ich weiß keine Speichermöglichkeit.
In dem Fall ist es einfach technisch aufwändiger, mir würden 2/3 Möglichkeiten einfallen:
1. Nach jeder Sychronisation direkt speichern, das hab ich aber schon mal versucht. Dabei hast du das Problem, dass die Datei bei einem vielen schnellen Schreibenzugriffen nicht rechtzeitig wieder vom Filesystem freigegeben wird und du musst mehrere Schreibversuche machen was nicht so geil ist:D
2. Wir haben einfachen einen gewissen Intervall bei dem er die Konfiguration abspeichern, finde auch suboptimal.
3. Wäre eine Kombination er speichert mit einem gewissen Delay ab und verhindert damit den Lock durch das Filesystem. Im schlimmsten fall verhält er sich bei dauer Änderung dann wie Variante 2.

Ist halt alles bissle gefummel bist das mal stabil läuft. Ich weiß nicht ob das so viel Sinn macht, da Zeit reinzuinvestieren.
Könnte man dann allerdings auch im Controller verwenden da hätten wir mit der Projektkonfiguration ein ähnliches Problem.

Mein Vorschlag wäre der __Name__ der Node wird im Projekt File gespeichert und die __Location__ ganz nomal in den AppSettings.json. Und jede Node hat einen internen eindeutigen Schlüssel. 
Ich denke das "need Configuration" bringt kein wirklichen Mehrwert.

**Comment by langmario** [comment]
+ Zustand "Syncing" für während die Dateien synchronisiert werden
